# Set up the Docker image and services for GitLab CI/CD
default:
  # Use the latest version of Docker
  image: docker:27.5.1
  # Use the Docker-in-Docker service for GitLab CI/CD
  services:
    - docker:27.5.1-dind
  # Check the Docker version
  before_script:
    - docker info

# Telling Docker where to create the certificates Docker creates on boot
variables:
  DOCKER_TLS_CERTDIR: "/certs"

stages:
  - build
  - test
  - deploy

job_build:
  stage: build
  script:
    - echo "Building the project"
    - docker compose -f docker-compose.yml build

job_test:
  stage: test
  script:
    - echo "Running tests"

job_deploy:
  stage: deploy
  script:
    - echo "Deploying the project"
    - docker compose up -d