services:
  service1:
    build: ./node-frontend
    environment:
      - PORT=8199
    deploy:
      replicas: 3
    networks:
      - containernetwork
    depends_on:
      - service2           

  service2:
    build: ./python-backend
    container_name: service2
    expose:
      - "5000"
    networks:
      - containernetwork
  nginx:
    build: ./nginx-webserver
    container_name: service3
    volumes:
      - ./nginx-webserver/site-content:/usr/data
    ports:
      - "8198:8198"
    networks:
      - containernetwork
    depends_on:
      - service1
      - service2

networks:
  containernetwork:
    driver: bridge
